export const config = {
  GW: 960,
  GH: 540,
  RUMBA_RADIUS: 30,
  RUMBA_MAX_SPEED: 1.5,
  RUMBA_ACCEL: 0.2,
  RUMBA_FRICTION: 0.86,
  CHAR_SIZE: 90,
  CHAR_FRICTION: 0.90,
  CHAR_STAND_H: 150,
  ATTACH_RANGE: 105,
  DETACH_RANGE: 200,
  SLIP_DURATION_SEC: 0.40,
  REATTACH_COOLDOWN_SEC: 0.25,
  DRAG_ANIM_FRAMES: 6,
  DRAG_ANIM_INTERVAL: 0.03,
  DRAG_ANIM_DURATION: 6 * 0.03,
  DRAG_DRAW_SIZE: 160,
  MACARON_DRAW_H: 40,
  MACARON_ATTRACT_FORCE: 0.35,
  TOTAL_MACARONS: 5,
  MACARON_SPEED: 0.8,
  DRAG_SPEED_BASE: 8,
  DRAG_SPEED_PENALTY: 2.5,
  CHAR_SIZE_GROW: 60,
  TOUCH_DEAD: 15,
  TOUCH_MAX: 80,
  WALL_COLOR: "#d4c4b8",
  WALL_BORDER: "#b89d88",
  MACARON_IMAGE_NAMES: ["makaron.png", "makaron2.png", "makaron3.png"],
  IMAGE_NAMES: [
    "ルンバ.png",
    "main.png",
    "dragging-1.png",
    "dragging-2.png",
    "dragging-3.png",
    "dragging-4.png",
    "dragging-5.png",
    "dragging-6.png",
    "dragging-7.png",
    "makaron.png",
    "makaron2.png",
    "makaron3.png",
    "goal.png",
    "gameover-image.png",
  ],
};
