export function createState() {
  return {
    viewport: {
      scale: 1,
      offsetX: 0,
      offsetY: 0,
      dpr: 1,
    },
    gameState: "title",
    rumbaX: 0,
    rumbaY: 0,
    rumbaVX: 0,
    rumbaVY: 0,
    rumbaFacingX: 1,
    rumbaFacingY: 0,
    dragFlipped: false,
    charX: 0,
    charY: 0,
    charVX: 0,
    charVY: 0,
    attached: false,
    hasBeenAttached: false,
    slipTimer: 0,
    reattachCooldown: 0,
    elapsedTime: 0,
    macarons: [],
    collectionEffects: [],
    ropePoints: [],
    screenShake: 0,
    dragAnimTimer: 0,
    gameOverTime: 0,
    clearTime: 0,
    macaronsEaten: 0,
    bestTime: parseFloat(localStorage.getItem("npochamu_best") || "0"),
    cryingTimer: 0,
    cryingTimerActive: false,
    particles: [],
    lastTime: 0,
  };
}
